### PR TITLE
 test Linux ProjFS non-null availability in callbacks and placeholder update methods

### PR DESCRIPTION
**Pull request by chrisd8088**
Commit 2f1fe70 introduced a `NullReferenceException` when using `MirrorProvider`, because the `MirrorProvider.FileSystemVirtualizer.TryStartVirtualizationInstance()` method only sets its `Enlistment` variable after the platform-specific `StartVirtualizationInstance()` method returns, we as we wait for the FUSE mount to succeed in the Linux `StartVirtualizationInstance()` method, another process may pre-emptively attempt to hydrate the top-level directory, leading to an `OnEnumerateDirectory()` callback which fails when it tries to access the `Enlistment` variable in
`MirrorProvider.FileSystemVirtualizer.GetFullPathInMirror()`:
```
Mounting /home/chrisd/TestRoot
OnEnumerateDirectory(0, '.', 2336, /usr/libexec/gvfs-udisks2-volume-monitor)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MirrorProvider.FileSystemVirtualizer.GetFullPathInMirror(String relativePath) in .../VFSForGit/MirrorProvider/MirrorProvider/FileSystemVirtualizer.cs:line 26
   at MirrorProvider.FileSystemVirtualizer.DirectoryExists(String relativePath) in .../VFSForGit/MirrorProvider/MirrorProvider/FileSystemVirtualizer.cs:line 31
   at MirrorProvider.Linux.LinuxFileSystemVirtualizer.OnEnumerateDirectory(UInt64 commandId, String relativePath, Int32 triggeringProcessId, String triggeringProcessName) in .../VFSForGit/MirrorProvider/MirrorProvider.Linux/LinuxFileSystemVirtualizer.cs:line 66
   at PrjFSLib.Linux.VirtualizationInstance.HandleProjEvent(Event& ev) in .../VFSForGit/ProjFS.Linux/PrjFSLib.Linux.Managed/VirtualizationInstance.cs:line 400
./MirrorProvider_Mount.sh: line 13: 12765 Aborted                 dotnet $BUILDDIR/MirrorProvider.Linux.dll mount "$TEST_ROOT"
```

This PR therefore tries the alternative approach [we discussed](https://github.com/github/VFSForGit/pull/24#discussion_r287174133) in #24, namely, checking for a `null` value of `this.projfs` in `HandleProjEvent()` in particular, and returning `ENODEV` in that case.  The other code changes are entirely defensive programming, and are not expected to actually be triggered under any circumstances, with the possible exception of the check in `HandleNonProjEvent()`, which does not use `this.projfs` but which could be asked to deliver an event to the provider before we have returned from `StartVirtualizationInstance()`.

### CODE REVIEW

**Comment by kivikakk** [comment]
Rebased!

**Review by kivikakk — APPROVED** [review]
I refactored the testing of `this.projfs` into a method that does this for us -- it means we can now (textually) audit that accesses to `this.projfs` are safe.

**Comment by kivikakk** [comment]
(Please feel free to merge if you're OK with this 👍)

**Comment by chrisd8088** [comment]
Thanks!  :+1:  Will merge shortly, and probably also squash everything down to a single commit (for the sake of those reviewing microsoft/VFSForGit#1125).

**Pull request merged**
